version: "3.8"

services:
  user_account:
    image: semirm/faceit-user:1
    build:
      context: .
      dockerfile: cmd/user/Dockerfile
    container_name: faceit_user
    command:
      - -rmq_host=faceit_rmq
      - -connStr=host=faceit_pg port=5432 dbname=faceit_db user=postgres password=postgres sslmode=disable
    ports:
      - "8001:8001"
    networks:
      - faceit
  account_listener:
    image: semirm/faceit-listener:1
    build:
      context: .
      dockerfile: cmd/listener/Dockerfile
    container_name: faceit_account_listener
    command:
      - -rmq_host=faceit_rmq
    depends_on:
      - rmq
    networks:
      - faceit
  gateway:
    image: semirm/faceit-gateway:1
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: faceit_gateway
    command:
      - -account_uri=faceit_user:8001
    ports:
      - "8000:8000"
    depends_on:
      - user_account
    networks:
      - faceit
  rmq:
    image: rabbitmq:management
    container_name: faceit_rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - faceit
  db:
    image: postgres:latest
    container_name: faceit_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=faceit_db
    ports:
      - "5432:5432"
    networks:
      - faceit
networks:
  faceit: